name = "EMD"
uuid = "02ac4aea-c29f-47d8-8f34-8c8291554982"
authors = ["Jordan S <46058723+jsmithnh09@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
